# @package _global_
defaults:
  - /habitat: habitat_config_base
  - /habitat/task: objectnav
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
  - /habitat/dataset/objectnav: mp3d
  - _self_

habitat:
  environment:
    max_episode_steps: 2000

  simulator:
    turn_angle: 30
    tilt_angle: 30
    action_space_config: "v1"
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
            hfov: 79
            position: [0, 1.25, 0]
          depth_sensor:
            width: 640
            height: 480
            hfov: 79
            min_depth: 0
            max_depth: 10.0
            position: [0, 1.25, 0]
        height: 1.25
        radius: 0.18
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: True
  task:
      measurements:
        distance_to_goal:
          type: DistanceToGoal
          distance_to: VIEW_POINTS
        success:
          type: Success
          success_distance: 0.25
        spl:
          type: SPL
  dataset:
    type: dialog
    split: unseen
    scenes_dir: VL-LN-Bench/scene_datasets
    data_path: VL-LN-Bench/raw_data/mp3d/train/train_iign.json.gz
