exp:
  num_environments: 1
  dump_location: datadump_qualitative
  exp_name: llava3d
  no_gpu: 0
  seed: 1
  visualize: True
  print_images: 0
  num_sem_categories: 10
  goal_type: object
  goal_map_only: False
  detector: mp3d_gt
  frame_width: 90
  frame_height: 160
  vocabulary: hm3d
  task: object

agent:
  max_steps: 500
  pointnav_stop_radius: 0.9
  num_goal_categories: 6
  use_vision_language_feat: False
  model_path: checkpoints/llava-v1.5-7b-waypoint-position-p-encoder
  conv_mode: llava_v1
  seq: ","
  temperature: 0.2
  top_p: null
  num_beams: 1
  max_new_tokens: 512
  semantic_map:
    semantic_categories: hm3d_9cat # "hm3d_90cat" #map semantic channel categories ("coco_indoor", "longtail_indoor", "mukul_indoor")
    num_sem_categories: 10           # number of map semantic channel categories (16, 257, 35)
    agent_height_project: False
    map_size_cm: 4800        # global map size (in centimeters)
    map_resolution: 5        # size of map bins (in centimeters)
    vision_range: 100        # diameter of local map region visible by the agent (in cells)
    global_downscaling: 2    # ratio of global over local map
    du_scale: 1              # frame downscaling before projecting to point cloud
    cat_pred_threshold: 5.0  # number of depth points to be in bin to classify it as a certain semantic category
    exp_pred_threshold: 1.0  # number of depth points to be in bin to consider it as explored
    map_pred_threshold: 0.1  # number of depth points to be in bin to consider it as obstacle
    explored_radius: 150     # radius (in centimeters) of visually explored region
    been_close_to_radius: 200  # radius (in centimeters) of been close to region
    must_explore_close: False
    min_obs_height_cm: 25    # minimum height (in centimeters) of obstacle to be considered as obstacle
    global_update_steps: 500
    # erosion and filtering to reduce the number of spurious artifacts
    dilate_obstacles: False
    dilate_size: 3
    dilate_iter: 1
    goal_reached_dist: 20